name: Go Tests

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'

      - name: Run tests
        run: make test
      
      # --- UPLOAD TO Sonarcube ---
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
      
      # --- UPLOAD TO Codecov ---
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: demo-app/results.out
          token: ${{ secrets.CODECOV_TOKEN }}

      # --- UPLOAD TO Codacy ---
      - name: Upload Coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          curl -Ls https://coverage.codacy.com/get.sh > codacy-reporter.sh
          chmod +x codacy-reporter.sh
          
          ./codacy-reporter.sh report \
            --force-coverage-parser go \
            -t "$CODACY_PROJECT_TOKEN" \
            -r demo-app/results.out
      
      # --- UPLOAD TO DEEPSOURCE ---
      - name: Report results to DeepSource
        run: |
          # 1. Install CLI
          curl https://deepsource.com/cli | sh
          
          # 2. Report coverage
          ./bin/deepsource report --analyzer test-coverage --key go --value-file ./demo-app/results.out
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
